#!/usr/bin/env bash
# Build Noita.app from the user's own Noita install. The recompiled code is derived from the game, so it is
# never shipped: this runs the discover/lift/build pipeline locally against the install's noita.exe and
# msvcp120.dll, then wraps build/mina4mac in an app bundle that runs the game from that install (it copies
# no game files; binaries and data/ are read in place, and logger.txt is written there, as on Windows).
# Saves live under ~/Library/Application Support/mina4mac/. The launcher log goes to ~/Library/Logs/mina4mac.log
# (the previous launches' in mina4mac.log.1 to .5, newest first).
# Usage: tools/package_app.sh [--no-build] [--fps] [--telemetry] [install dir]
#   install: $NOITA_SRC, default the Sikarugir Wine prefix's GOG install (as tools/setup_game.sh)
#   output: $MINA4MAC_APP, default build/Noita.app (gitignored; copy it anywhere, e.g. ~/Applications)
#   --no-build: reuse the existing build/mina4mac (it must have been built from the same exe)
#   --fps: the app shows fps and the worst frame time in the window title (MINA4MAC_FPS=1; not in fullscreen)
#   --telemetry: --fps, plus the playtest mod tools/telemetry, installed into the install's mods/ and enabled in
#     the app's save, so each [fps] line in the log also names the frame, biome, position and nearby entities
#     (the game drops mods it can't find from the save's list, so run this again after benchmark runs in build/game)
# Bundles Homebrew's SDL2 and, if tools/setup_fmod.sh ran, the FMOD dylibs (else audio is the silent stub).
set -euo pipefail
cd "$(dirname "$0")/.."
BUILD=1 FPS= TELEMETRY=0
while [ $# -gt 0 ]; do
    case "$1" in
    --no-build) BUILD=0 ;;
    --fps) FPS='export MINA4MAC_FPS="${MINA4MAC_FPS:-1}"' ;;
    --telemetry) FPS='export MINA4MAC_FPS="${MINA4MAC_FPS:-1}"' TELEMETRY=1 ;;
    *) break ;;
    esac
    shift
done
SRC=${1:-${NOITA_SRC:-"$HOME/Applications/Noita Sikarugir.app/Contents/SharedSupport/prefix/drive_c/GOG Games/Noita"}}
APP=${MINA4MAC_APP:-build/Noita.app}

# The runtime is written against one build of the game (Jan 25 2025, GOG): check the binaries it recompiles.
check() {  # check <file> <sha256>
    [ -f "$SRC/$1" ] || { echo "no Noita install at $SRC ($1 missing)"; exit 1; }
    [ "$(shasum -a 256 "$SRC/$1" | cut -d' ' -f1)" = "$2" ] ||
        { echo "$SRC/$1 is not the supported build (Noita, Build Jan 25 2025, GOG)"; exit 1; }
}
check noita.exe f0f5ffd1c64558663ac7cffaf689f4899732a56494c3530b806bf3357d094363
check msvcp120.dll 87c42ca155473e4e71857d03497c8cbc28fa8ff7f2c8d72e8a1f39b71078f608
[ -f "$SRC/data/data.wak" ] || { echo "no Noita install at $SRC (data/data.wak missing)"; exit 1; }
SRC=$(cd "$SRC" && pwd)
made_here() {  # made by this script (NoitamacGameDir: before the project was renamed)
    local k; for k in Mina4macGameDir NoitamacGameDir; do
        /usr/libexec/PlistBuddy -c "Print :$k" "$APP/Contents/Info.plist" >/dev/null 2>&1 && return 0
    done; return 1
}
if [ -e "$APP" ] && ! made_here; then
    echo "refusing to overwrite $APP: it wasn't made by this script"; exit 1
fi

if [ $BUILD = 1 ]; then
    export NOITA_DIR="$SRC"  # tools/pe.py reads the modules from here
    for m in noita msvcp120; do
        [ -f "build/$m/discover.pkl" ] || uv run tools/discover.py "$m"
    done
    uv run tools/build_all.py
fi
[ -x build/mina4mac ] || { echo "build/mina4mac is missing (run without --no-build)"; exit 1; }

TMP="$APP.tmp"
rm -rf "$TMP"
mkdir -p "$TMP/Contents/MacOS" "$TMP/Contents/Frameworks" "$TMP/Contents/Resources"
C="$TMP/Contents"
cp build/mina4mac "$C/MacOS/mina4mac"
sdl=$(otool -L build/mina4mac | awk '/libSDL2/ {print $1}')
cp -L "$sdl" "$C/Frameworks/"
chmod u+w "$C/Frameworks/$(basename "$sdl")"
install_name_tool -id "@executable_path/../Frameworks/$(basename "$sdl")" "$C/Frameworks/$(basename "$sdl")"
install_name_tool -change "$sdl" "@executable_path/../Frameworks/$(basename "$sdl")" "$C/MacOS/mina4mac"
fmod=no
if [ -f build/fmod_api/lib/libfmodstudio.dylib ]; then
    cp build/fmod_api/lib/libfmod.dylib build/fmod_api/lib/libfmodstudio.dylib "$C/Frameworks/"
    fmod=yes
fi
icon=$(ls "$SRC"/goggame-*.ico 2>/dev/null | head -1 || true)
[ -n "$icon" ] && sips -s format icns "$icon" --out "$C/Resources/Noita.icns" >/dev/null

# The bundle's executable: point the launcher at the install, keep the display awake (with it asleep,
# SDL_GL_SwapWindow blocks on vsync) and log to ~/Library/Logs. NOITA_DIR/MINA4MAC_* from the environment win.
q=$(printf %q "$SRC")
cat >"$C/MacOS/Noita" <<EOF
#!/bin/bash
# Generated by mina4mac's tools/package_app.sh.
C="\$(cd "\$(dirname "\$0")/.." && pwd)"
GAME=$q  # the install this app was built from
export NOITA_DIR="\${NOITA_DIR:-\$GAME}"
if [ ! -f "\$NOITA_DIR/noita.exe" ]; then
    /usr/bin/osascript -e "display alert \"Noita install not found\" message \"No noita.exe in \$NOITA_DIR. Rebuild the app with tools/package_app.sh.\"" >/dev/null
    exit 1
fi
[ -f "\$C/Frameworks/libfmodstudio.dylib" ] && export MINA4MAC_FMOD="\${MINA4MAC_FMOD:-\$C/Frameworks}"
$FPS
LOG="\$HOME/Library/Logs/mina4mac.log"
mkdir -p "\$HOME/Library/Logs"
for i in 4 3 2 1; do  # keep the last 5 launches' logs (a crash, a playtest): mina4mac.log.1 (newest) to .5
    [ -f "\$LOG.\$i" ] && mv -f "\$LOG.\$i" "\$LOG.\$((i + 1))"
done
[ -f "\$LOG" ] && mv -f "\$LOG" "\$LOG.1"
exec /usr/bin/caffeinate -d -u "\$C/MacOS/mina4mac" "\$@" >"\$LOG" 2>&1
EOF
chmod +x "$C/MacOS/Noita"

cat >"$C/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key><string>Noita</string>
    <key>CFBundleIdentifier</key><string>local.mina4mac.Noita</string>
    <key>CFBundleName</key><string>Noita</string>
    <key>CFBundlePackageType</key><string>APPL</string>
    <key>CFBundleIconFile</key><string>Noita</string>
    <key>CFBundleShortVersionString</key><string>$(git rev-parse --short HEAD)</string>
    <key>CFBundleVersion</key><string>1</string>
    <key>LSMinimumSystemVersion</key><string>14.0</string>
    <key>LSApplicationCategoryType</key><string>public.app-category.games</string>
    <key>NSHighResolutionCapable</key><true/>
    <key>Mina4macGameDir</key><string>$(sed 's/&/\&amp;/g; s/</\&lt;/g' <<<"$SRC")</string>
</dict>
</plist>
EOF

# install_name_tool invalidated the linker's ad-hoc signatures; Apple silicon won't run unsigned code.
codesign -s - -f "$C/Frameworks/"*.dylib "$C/MacOS/mina4mac"
codesign -s - -f "$TMP"
rm -rf "$APP"
mv "$TMP" "$APP"
echo "$APP: game $SRC, FMOD $fmod ($(du -sh "$APP" | cut -f1))"

# The app's save (AppData under ~/Library/Application Support/mina4mac, as runtime/shell32.c maps it).
SAVE="$HOME/Library/Application Support/mina4mac/AppData/LocalLow/Nolla_Games_Noita/save00/mod_config.xml"
if [ $TELEMETRY = 1 ]; then
    rsync -a --delete tools/telemetry/ "$SRC/mods/mina4mac_telemetry/"
    if [ ! -f "$SAVE" ]; then
        echo "telemetry: installed, but there is no $SAVE yet: start the app once, quit, and run this again"
    elif grep -q 'name="mina4mac_telemetry"' "$SAVE"; then
        sed -i '' -E 's/<Mod enabled="[01]" name="mina4mac_telemetry"/<Mod enabled="1" name="mina4mac_telemetry"/' "$SAVE"
    else
        sed -i '' 's#</Mods>#  <Mod enabled="1" name="mina4mac_telemetry" settings_fold_open="0" workshop_item_id="0" >\
  </Mod>\
</Mods>#' "$SAVE"
    fi
    echo "telemetry: mods/mina4mac_telemetry in $SRC, enabled in the app's save"
fi
# The benchmark mods pin the seed (perfbench also floods the world): tools/perfbench.sh enables its mod only
# while it runs, but a killed run can leave it on; seedprint stays on until tools/determinism.sh remove.
for m in perfbench seedprint; do
    [ -d "$SRC/mods/$m" ] && grep -q "<Mod enabled=\"1\" name=\"$m\"" "$SAVE" 2>/dev/null &&
        echo "warning: the $m mod is installed in $SRC and enabled in the app's save (disable it in the mod menu or with its tool's remove)"
done
true
